steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/inventory-repo/my-go-app:$COMMIT_SHA' # Changed my-go-repo to inventory-repo
    - '.'
    - '-f'
    - 'Dockerfile'
  id: 'Build Image'

# Step 2: Push the Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/inventory-repo/my-go-app:$COMMIT_SHA' # Changed my-go-repo to inventory-repo
  id: 'Push Image'

# Step 3: Deploy the image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'my-go-service' # Your desired Cloud Run service name
    - '--image'
    - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/inventory-repo/my-go-app:$COMMIT_SHA' # Changed my-go-repo to inventory-repo
    - '--region'
    - 'southamerica-east1' # Ensure this is your correct region
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated' # Optional: Allows unauthenticated access
    - '--set-env-vars=CURRENT_TIME=$(date +%Y-%m-%d_%H-%M-%S)' # Example environment variable
  id: 'Deploy to Cloud Run'

images:
- 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/inventory-repo/my-go-app:$COMMIT_SHA' # Changed my-go-repo to inventory-repo

options:
  logging: CLOUD_LOGGING_ONLY
